
<!-- PITCHER_START -->

# pitcherProweb

![Type](https://pitcherprobadges.onrender.com/api/badge?label=Type&value=Frontend%20Web%20Application&color=a855f7&labelColor=334155&style=for-the-badge) ![Files](https://pitcherprobadges.onrender.com/api/badge?label=Files&value=5&color=f97316&labelColor=334155&style=for-the-badge) ![Lines of Code](https://pitcherprobadges.onrender.com/api/badge?label=LOC&value=900&color=22c55e&labelColor=334155&style=for-the-badge)

![HTML5](https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white) ![CSS3](https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white) ![JavaScript](https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black)

---

## Overview

**pitcherProweb** is a **Frontend Web Application** built using **HTML, CSS, JavaScript**. The codebase comprises **5 source files** totaling **900 lines of code**.

---

## Preview

![Pitcher Icon](./assets/pitcher-icon.png)<br>
<sub>*Pitcher Icon*</sub>

---

##    Prerequisites

Make sure you have the following ready:

- **Modern Web Browser**: Google Chrome, Mozilla Firefox, Microsoft Edge, or Safari
- **Code Editor**: [VS Code](https://code.visualstudio.com/) (Recommended)
- **VS Code Extension**: [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) (Optional, for live preview)

---

##   Installation Guide

Follow these simple steps to set up the project locally:

1. **Clone the repository:**
   ```bash
   git clone <repository-url>
   cd pitcherProweb
   ```

2. **Open the project in VS Code:**
   ```bash
   code .
   ```

3. **No package installation required.** You can launch directly via Live Server or open `index.html` in any modern browser.

---

##  How to Run

### Option 1: Direct Browser
Double click on `index.html` file to open it directly in any browser.

### Option 2: Live Server (VS Code)
1. Open project in VS Code (`code .`).
2. Right click on `index.html`.
3. Click on **"Open with Live Server"**.

---

## Technology Stack

- HTML
- CSS
- JavaScript

---

## Folder Structure

```text
pitcherProweb/
├── assets
│   ├── main.js (3.6 KB)
│   ├── pitcher-icon.png (9.6 KB)
│   └── styles.css (19.5 KB)
├── index.html (379.6 KB)
└── README.md (3.0 KB)
```

---

## Project Statistics

- **Total Files & Folders:** **5** files in **2** folders
- **Project Size:** **415.3 KB** 
- **Source Code (LOC):** 900 lines
- **Code Composition:** 84.9% Code • 8.6% Comments • 6.5% Blanks
- **File Extensions:** `.js` (1) • `.png` (1) • `.css` (1) • `.html` (1) • `.md` (1)

### Key Files & Sizes
- `index.html` — **379.6 KB** (422 lines)
- `assets/styles.css` — **19.5 KB** (392 lines)
- `assets/pitcher-icon.png` — **9.6 KB**
- `assets/main.js` — **3.6 KB** (86 lines)
- `README.md` — **3.0 KB** (73 lines)


---

## Author

**Author:** Himanshu   
Last Updated: 07 / 09 / 2026 at 03:23 PM  
Documentation generated by [PitcherPro](https://sefard01.github.io/pitcherProweb/)


<!-- PITCHER_END -->
